export const styles = {
  app:         { display:"flex", flexDirection:"column", height:"100vh", overflow:"hidden", background:"#06090d", color:"#c8d8e4", fontFamily:"'Courier New',monospace" },
  toast:       { position:"fixed", top:12, left:"50%", transform:"translateX(-50%)", zIndex:9999, padding:"10px 20px", fontSize:12, letterSpacing:1, borderRadius:2 },

  header:      { display:"flex", alignItems:"center", gap:16, padding:"0 16px", height:52, background:"#09111a", borderBottom:"1px solid #1a2a35", flexShrink:0 },
  brand:       { display:"flex", alignItems:"center", gap:10 },
  brandIcon:   { fontSize:22, color:"#00d084", lineHeight:1 },
  brandName:   { fontSize:15, fontWeight:"bold", letterSpacing:4, color:"#00d084" },
  brandSub:    { fontSize:8, color:"#3a5262", letterSpacing:2 },
  nav:         { display:"flex", gap:3, flex:1 },
  navBtn:      { background:"transparent", border:"1px solid #1a2535", color:"#3a5262", padding:"5px 12px", cursor:"pointer", fontFamily:"inherit", fontSize:10, letterSpacing:2 },
  navBtnOn:    { background:"#00d08412", border:"1px solid #00d08450", color:"#00d084" },
  statusBar:   { fontSize:10, color:"#3a5262", display:"flex", alignItems:"center", gap:6, letterSpacing:1, whiteSpace:"nowrap" },
  statusDot:   { width:5, height:5, borderRadius:"50%", background:"#00d084", boxShadow:"0 0 5px #00d084", display:"inline-block" },
  saveBtn:     { background:"#00d08422", border:"1px solid #00d084", color:"#00d084", padding:"6px 14px", cursor:"pointer", fontFamily:"inherit", fontSize:10, letterSpacing:1, flexShrink:0 },

  mapLayout:   { display:"flex", flex:1, overflow:"hidden" },
  toolbar:     { width:148, background:"#09111a", borderRight:"1px solid #1a2a35", padding:12, display:"flex", flexDirection:"column", gap:14, overflowY:"auto", flexShrink:0 },
  toolBtn:     { background:"transparent", border:"1px solid #1a2535", color:"#7a9aaa", padding:"6px 8px", cursor:"pointer", fontFamily:"inherit", fontSize:10, textAlign:"left", letterSpacing:1 },
  toolBtnOn:   { background:"#00d08412", border:"1px solid #00d08450", color:"#00d084" },
  toolBtnDanger:{ background:"transparent", border:"1px solid #3a1a1a", color:"#ef444466", padding:"6px 8px", cursor:"pointer", fontFamily:"inherit", fontSize:10, textAlign:"left", letterSpacing:1 },
  hint:        { fontSize:9, color:"#3a5262", lineHeight:1.7, padding:"5px 0 0 8px", borderLeft:"2px solid #1a2535" },
  numInput:    { background:"#0d1520", border:"1px solid #1a2a35", color:"#c8d8e4", padding:"4px 6px", fontFamily:"inherit", fontSize:11, width:"100%", boxSizing:"border-box" },
  miniLabel:   { fontSize:9, color:"#3a5262", letterSpacing:2, marginBottom:2 },
  canvasWrap:  { flex:1, display:"flex", alignItems:"center", justifyContent:"center", background:"#04060a", position:"relative", overflow:"hidden" },
  canvas:      { display:"block", maxWidth:"100%", maxHeight:"100%" },
  mapFoot:     { position:"absolute", bottom:6, right:10, fontSize:9, color:"#1e3040", letterSpacing:1, pointerEvents:"none" },
  sidePanel:   { width:210, background:"#09111a", borderLeft:"1px solid #1a2a35", overflowY:"auto", flexShrink:0 },

  inp:         { background:"#0d1520", border:"1px solid #1a2a35", color:"#c8d8e4", padding:"5px 7px", fontFamily:"inherit", fontSize:11, width:"100%", boxSizing:"border-box" },
  deleteBtnFull:{ background:"transparent", border:"1px solid #3a1a1a", color:"#ef444466", padding:"7px", cursor:"pointer", fontFamily:"inherit", fontSize:10, width:"100%", letterSpacing:1, marginTop:4 },
  empty:       { display:"flex", flexDirection:"column", alignItems:"center", justifyContent:"center", height:"100%", color:"#3a5262", textAlign:"center" },

  camTab:      { flex:1, display:"flex", flexDirection:"column", overflow:"hidden" },
  camTabHeader:{ display:"flex", justifyContent:"space-between", alignItems:"center", padding:"12px 18px", borderBottom:"1px solid #1a2a35" },
  addBtn:      { background:"#00d08412", border:"1px solid #00d08450", color:"#00d084", padding:"6px 14px", cursor:"pointer", fontFamily:"inherit", fontSize:10, letterSpacing:1 },
  camCards:    { flex:1, overflowY:"auto", padding:"10px 18px", display:"flex", flexDirection:"column", gap:6 },
  card:        { background:"#09111a", borderLeft:"3px solid", border:"1px solid #1a2a35" },
  cardRow:     { display:"flex", alignItems:"center", gap:10, padding:"10px 14px", cursor:"pointer", userSelect:"none" },

  ghostBtn:    { background:"transparent", border:"1px solid #1a2535", color:"#7a9aaa", padding:"6px 14px", cursor:"pointer", fontFamily:"inherit", fontSize:10, letterSpacing:1 },
  accentBtn:   { background:"#00d08412", border:"1px solid #00d08450", color:"#00d084", padding:"6px 14px", cursor:"pointer", fontFamily:"inherit", fontSize:10, letterSpacing:1 },

  streamsTab:  { flex:1, display:"flex", flexDirection:"column", overflow:"hidden" },
  streamsGrid: { flex:1, overflowY:"auto", padding:16, display:"grid", gridTemplateColumns:"repeat(auto-fill,minmax(440px,1fr))", gap:12, alignContent:"start" },
  streamCard:  { background:"#09111a", border:"1px solid #1a2a35", display:"flex", flexDirection:"column" },
  streamHeader:{ display:"flex", alignItems:"center", gap:8, padding:"8px 12px", borderBottom:"1px solid #1a2a35", borderLeft:"3px solid" },
  streamImgWrap:{ position:"relative", background:"#040608", minHeight:160 },
  streamImg:   { width:"100%", display:"block" },
  streamNoTrack:{ position:"absolute", inset:0, display:"flex", alignItems:"center", justifyContent:"center", fontSize:10, color:"#3a5262" },
  streamFooter:{ padding:"6px 12px", display:"flex", gap:6, flexWrap:"wrap", minHeight:30, alignItems:"center" },
  trackBadge:  { fontSize:10, background:"#ef444422", color:"#ef4444", border:"1px solid #ef444444", padding:"2px 8px", borderRadius:2 },
};
